### ISSUE TITLE
Program terminated with signal 8, Arithmetic exception（div zero）

### ISSUE THREAD

**Issue by leewill1120** [troydhanson/uthash#129] opened 2017-07-17 12:31 UTC
when I HASH_ADD_STR()， the  program terminated with zero-div in HASH_EXPAND_BUCKETS
![image](https://user-images.githubusercontent.com/16256642/28268080-68dfd6f8-6b2f-11e7-9d64-f42023642a5e.png)
#define UTHASH_VERSION 2.0.2

**Comment by Quuxplusone** [comment] 2017-07-17 16:58
- Can you provide a complete, compileable example?
- - If not, can you reproduce the crash at all? 
- - - If so, what are the values of `ideal_chain_maxlen`, `_he_newbkt->count`, `tbl->num_buckets`, and `tbl->nonideal_items` at the time of the crash?
- (Approximately) how many inserts did you do before the crash? (If the answer is more than a billion, I consider this not-a-bug, sorry; unless you have a specific patch in mind.)

**Comment by Quuxplusone** [comment] 2017-11-27 20:01
Closing as "cannot reproduce"; feel free to reopen this issue if it *can* be reproduced.

**Closed by Quuxplusone** 2017-11-27 20:01 UTC
