### ISSUE TITLE
Provide a release tarball

### ISSUE THREAD

**Issue by fcambus** [troydhanson/uthash#152] opened 2018-04-04 22:51 UTC
It would be nice if you would consider adding proper source release tarballs,
as GitHub auto-generated tarballs are not immutable. This is an issue [1] for
operating systems creating packages for uthash. Thanks in advance.

[1] https://marc.info/?l=openbsd-ports&m=151973450514279&w=2

**Comment by Quuxplusone** [comment] 2018-04-04 23:40
Hi @fcambus! As I understand it, there are two ways to get a "stable" tarball of uthash right now:

- `git clone https://github.com/troydhanson/uthash uthash-v2.0.2 ; git --work-tree uthash-v2.0.2 checkout v2.0.2 ; tar --exclude */.git -zcf v2.0.2.tar.gz uthash-v2.0.2`
- `curl -OL https://github.com/troydhanson/uthash/archive/v2.0.2.tar.gz`

The latter is *definitely* easier, but the former is always possible.

No matter what, you'll have to make a DNS lookup for `github.com` and then send some HTTP requests to `github.com`'s servers, both of which are complicated processes completely outside of uthash's control. If you're worried about what happens when GitHub is down, or what happens when they change their hosting policies... well, that would suck, but I can't see anything that the uthash project could possibly do about it in advance.

Or did you mean something else by "immutable"?  And what would constitute a "proper" tarball IYHO?

**Comment by Quuxplusone** [comment] 2018-04-15 05:54
I'm going to go ahead and close this as a duplicate of https://github.com/Homebrew/homebrew-core/issues/18044, with the same fix/workaround/whatever, which is "if you don't like how the server responds when you curl GitHub, either complain to GitHub Support or else stop curling GitHub." (And from that very active issue, it sounds like Homebrew is already doing a little of both.)

**Closed by Quuxplusone** 2018-04-15 05:54 UTC

**Comment by fcambus** [comment] 2018-04-23 14:06
I think there is some confusion here, my concern was not about GitHub
being down or changing hosting policies, neither it is about how the
servers responds.

My only concern is that the auto-generated tarball [1] is not guaranted
to always be the same, and it's checksum can change. This isn't an
issue for people downloading the release manually from GitHub, but it
is an issue for operating systems creating packages for uthash.

Would it be possible for you to download the auto-generated tarball [1]
and upload it as a release asset? This way, the file is guaranteed to
always be immutable. You can have a look here [2] for an example.

Thanks in advance.

[1] https://github.com/troydhanson/uthash/archive/v2.0.2.tar.gz
[2] https://github.com/fcambus/logswan/releases

**Comment by Quuxplusone** [comment] 2018-04-25 20:58
I see that https://github.com/fcambus/logswan/releases looks significantly different from https://github.com/troydhanson/uthash/releases, but I don't know how to make https://github.com/troydhanson/uthash/releases look the same as https://github.com/fcambus/logswan/releases. I see a button on https://github.com/troydhanson/uthash/releases that says "Draft a new release", but it's not obvious to me what would happen if I clicked it.

It sounds like GitHub is generating the release tarball in any event; you're just saying that GitHub will do something a bit smarter if I jump through the hoop of downloading and re-uploading the tarball to that area of their site? I'd still prefer to just let GitHub sort it out (like, they could provide that smarter behavior by default).

Alternatively, if logswan depends on a specific version of uthash, would it make sense for logswan to check a tarball into their repo? and/or to use a git submodule pinned to a specific commit SHA?
