### ISSUE TITLE
Add some MACROS LIKE LL_REVERSE() to support reverse the list

### ISSUE THREAD

**Issue by govc** [troydhanson/uthash#263] opened 2024-08-21 14:04 UTC
Please Add some macros to support reverse the list.
`
struct item{
    int id;
    struct item*next;
};

struct item*head = NULL;
void additem(int id)
{
    struct item*i = malloc(sizeof(*i));
    i->id = id;
   LL_PREPEND(head, i);
}

void add()
{
    for(int i=0; i<1000000; i++)
         additem(i);
}

int main(){
    add();
    LL_REVERSE(head);
    return 0;
}

`

**Comment by Quuxplusone** [comment] 2024-08-21 16:39
Closing as a duplicate of #197. I'm still amenable to such an addition; I just haven't had time or inclination to work on it specifically. Patches are still welcome.

**Closed by Quuxplusone** 2024-08-21 16:39 UTC
